"""Import every model so Base.metadata is fully populated (needed for
Alembic autogenerate) and so `from app.models import X` works anywhere."""

from app.models.base import Base
from app.models.geography import (
    Campus,
    CampusEstate,
    County,
    Estate,
    InternetProvider,
    PointOfInterest,
    SourceRecord,
    SubCounty,
    Town,
    TransportStop,
    University,
    UniversityAlias,
    VerificationEvent,
)
from app.models.identity import (
    IdentityDocument,
    ManagerProfile,
    Organisation,
    OrganisationMember,
    PayoutAccount,
    Permission,
    Role,
    RolePermission,
    User,
    UserDevice,
    UserProfile,
    UserRole,
    UserSession,
    VerificationCase,
)
from app.models.properties import (
    Amenity,
    AvailabilityPeriod,
    AvailabilitySnapshot,
    BedOrSpace,
    Building,
    CancellationPolicy,
    Deposit,
    Fee,
    FloorPlan,
    HouseRule,
    ListingReport,
    ListingVerificationBadge,
    ListingVersion,
    Media,
    PricingRule,
    Property,
    PropertyAmenity,
    PropertyCampus,
    PropertyCategory,
    PropertyUtility,
    TenancyTemplate,
    TenancyTemplateVersion,
    Unit,
    UnitAmenity,
    UnitCategory,
    Utility,
    VirtualTour,
)
from app.models.bookings import (
    Agreement,
    AgreementSignatory,
    AgreementVersion,
    Booking,
    BookingGuest,
    BookingHold,
    BookingInstallment,
    BookingQuote,
    Chargeback,
    LedgerAccount,
    LedgerEntry,
    Payment,
    PaymentAllocation,
    PaymentAttempt,
    PaymentCallback,
    Payout,
    ReconciliationRun,
    Receipt,
    Refund,
    SignatureEvent,
    SignatureRequest,
    SignedDocument,
)
from app.models.engagement import (
    AdminNote,
    AuditLog,
    BlogPost,
    Favourite,
    MaintenanceRequest,
    Notification,
    NotificationPreference,
    Review,
    ReviewCategory,
    ReviewResponse,
    SavedSearch,
    SearchAlert,
    SecurityEvent,
    SupportMessage,
    SupportTicket,
)
from app.models.staging import (
    RawFieldIssue,
    RawImportBatch,
    RawPropertyRecord,
    RawUniversityRecord,
)

__all__ = [
    "Base",
    # geography
    "County", "SubCounty", "Town", "Estate", "University", "UniversityAlias",
    "Campus", "CampusEstate", "PointOfInterest", "TransportStop",
    "InternetProvider", "SourceRecord", "VerificationEvent",
    # identity
    "User", "UserProfile", "UserSession", "UserDevice", "Role", "Permission",
    "RolePermission", "UserRole", "Organisation", "OrganisationMember",
    "ManagerProfile", "IdentityDocument", "VerificationCase", "PayoutAccount",
    # properties
    "Property", "Building", "Unit", "BedOrSpace", "PropertyCategory",
    "UnitCategory", "Amenity", "PropertyAmenity", "UnitAmenity", "Utility",
    "PropertyUtility", "Media", "FloorPlan", "VirtualTour", "PropertyCampus",
    "AvailabilityPeriod", "AvailabilitySnapshot", "ListingVersion",
    "ListingVerificationBadge", "ListingReport", "PricingRule", "Deposit",
    "Fee", "CancellationPolicy", "HouseRule", "TenancyTemplate",
    "TenancyTemplateVersion",
    # bookings
    "BookingQuote", "BookingHold", "Booking", "BookingGuest",
    "BookingInstallment", "Payment", "PaymentAttempt", "PaymentCallback",
    "PaymentAllocation", "Refund", "Chargeback", "Receipt", "Payout",
    "LedgerAccount", "LedgerEntry", "ReconciliationRun", "Agreement",
    "AgreementVersion", "AgreementSignatory", "SignatureRequest",
    "SignatureEvent", "SignedDocument",
    # engagement
    "Favourite", "SavedSearch", "SearchAlert", "Review", "ReviewCategory",
    "ReviewResponse", "BlogPost", "SupportTicket", "SupportMessage",
    "MaintenanceRequest", "Notification", "NotificationPreference",
    "AuditLog", "SecurityEvent", "AdminNote",
    # staging
    "RawImportBatch", "RawPropertyRecord", "RawUniversityRecord", "RawFieldIssue",
]
